[package]
name = "impulse"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]
ureq = { version = "^1.3", features = ["json"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
anyhow = "^1"
argh = "^0.1"